from ij import IJ
import os

"""
Computes orientation vector fields from .tif images using OrientationJ
in ImageJ/Fiji and exports the resulting vector tables as CSV files.

Inputs:
    input_folder  : path to the folder containing .tif images
    output_folder : path to the folder where CSV results will be saved

Parameters:
    Grid   : list of vector grid spacings used by OrientationJ
    Tensor : list of tensor sizes used for the structure tensor computation

Outputs:
    CSV files saved in output_folder containing the vector field table
    generated by OrientationJ for each image and parameter combination.

Notes:
    - The script scans input_folder recursively to find all .tif images.
    - For each image, the OrientationJ "Vector Field" command is executed.
    - The resulting table (vector positions and orientations) is exported
      as a CSV file.
    - The output filename encodes the tensor size and grid spacing used
      for the computation.
"""

input_folder = r"Path to images"
output_folder = r"Path to images"


if not os.path.exists(output_folder):
    os.makedirs(output_folder)


# --- Find all .tif files in the input folder ---
tif_files_path = []
tif_files_names = []

for root, dirs, files in os.walk(input_folder):
    for file in files:
        if file.endswith(".tif"):
            tif_files_path.append(os.path.join(root, file))
            tif_files_names.append(file)


# --- OrientationJ parameters ---
# Grid: spacing between vectors in the vector field
Grid = ['10']

# Tensor: structure tensor size used for orientation computation
Tensor = ['50']


print(tif_files_names)


# --- Loop over all images ---
for file in range(len(tif_files_names)):

    filename = tif_files_names[file]
    filepath = tif_files_path[file]

    IJ.open(filepath)
    IJ.selectWindow(filename)

    # --- Run OrientationJ vector field computation ---
    for tensor in Tensor:
        for grid in Grid:

            inp2 = "tensor=" + str(tensor) + \
                   " gradient=0  radian=on  vectorgrid=" + str(grid) + \
                   "  vectorscale=80.0 vectortype=0 vectoroverlay=on vectortable=on "

            IJ.run("OrientationJ Vector Field", inp2)

            result_name = "Tensor_" + str(tensor) + "_Grid_" + str(grid) + "_" + str(filename) + ".csv"
            output_path = os.path.join(output_folder, result_name)

            IJ.renameResults("OJ-Table-Vector-Field-", output_path)
            IJ.saveAs("Results", output_path)

            IJ.selectWindow(result_name)
            IJ.run("Close")

    IJ.run("Close All")